// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.quancheng.saluki.serializer.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string street = 1;</code>
     */
    java.lang.String getStreet();
    /**
     * <code>optional string street = 1;</code>
     */
    com.google.protobuf.ByteString
        getStreetBytes();

    /**
     * <code>optional string city = 2;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 2;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>optional string stateOrProvince = 3;</code>
     */
    java.lang.String getStateOrProvince();
    /**
     * <code>optional string stateOrProvince = 3;</code>
     */
    com.google.protobuf.ByteString
        getStateOrProvinceBytes();

    /**
     * <code>optional string country = 4;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>optional string country = 4;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>optional string postalCode = 5;</code>
     */
    java.lang.String getPostalCode();
    /**
     * <code>optional string postalCode = 5;</code>
     */
    com.google.protobuf.ByteString
        getPostalCodeBytes();

    /**
     * <code>optional bool isCanada = 6;</code>
     */
    boolean getIsCanada();

    /**
     * <code>map&lt;string, string&gt; mapTest = 7;</code>
     */
    int getMapTestCount();
    /**
     * <code>map&lt;string, string&gt; mapTest = 7;</code>
     */
    boolean containsMapTest(
        java.lang.String key);
    /**
     * Use {@link #getMapTestMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMapTest();
    /**
     * <code>map&lt;string, string&gt; mapTest = 7;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMapTestMap();
    /**
     * <code>map&lt;string, string&gt; mapTest = 7;</code>
     */

    java.lang.String getMapTestOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; mapTest = 7;</code>
     */

    java.lang.String getMapTestOrThrow(
        java.lang.String key);

    /**
     * <code>optional .Address.PhoneType phoneType = 8;</code>
     */
    int getPhoneTypeValue();
    /**
     * <code>optional .Address.PhoneType phoneType = 8;</code>
     */
    com.quancheng.saluki.serializer.proto.Message.Address.PhoneType getPhoneType();
  }
  /**
   * Protobuf type {@code Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      street_ = "";
      city_ = "";
      stateOrProvince_ = "";
      country_ = "";
      postalCode_ = "";
      isCanada_ = false;
      phoneType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              street_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              stateOrProvince_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              postalCode_ = s;
              break;
            }
            case 48: {

              isCanada_ = input.readBool();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                mapTest_ = com.google.protobuf.MapField.newMapField(
                    MapTestDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              mapTest = input.readMessage(
                  MapTestDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              mapTest_.getMutableMap().put(mapTest.getKey(), mapTest.getValue());
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              phoneType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.quancheng.saluki.serializer.proto.Message.internal_static_Address_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetMapTest();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.quancheng.saluki.serializer.proto.Message.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.quancheng.saluki.serializer.proto.Message.Address.class, com.quancheng.saluki.serializer.proto.Message.Address.Builder.class);
    }

    /**
     * Protobuf enum {@code Address.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.quancheng.saluki.serializer.proto.Message.Address.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Address.PhoneType)
    }

    private int bitField0_;
    public static final int STREET_FIELD_NUMBER = 1;
    private volatile java.lang.Object street_;
    /**
     * <code>optional string street = 1;</code>
     */
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      }
    }
    /**
     * <code>optional string street = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    private volatile java.lang.Object city_;
    /**
     * <code>optional string city = 2;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>optional string city = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATEORPROVINCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object stateOrProvince_;
    /**
     * <code>optional string stateOrProvince = 3;</code>
     */
    public java.lang.String getStateOrProvince() {
      java.lang.Object ref = stateOrProvince_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stateOrProvince_ = s;
        return s;
      }
    }
    /**
     * <code>optional string stateOrProvince = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStateOrProvinceBytes() {
      java.lang.Object ref = stateOrProvince_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stateOrProvince_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 4;
    private volatile java.lang.Object country_;
    /**
     * <code>optional string country = 4;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>optional string country = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSTALCODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object postalCode_;
    /**
     * <code>optional string postalCode = 5;</code>
     */
    public java.lang.String getPostalCode() {
      java.lang.Object ref = postalCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        postalCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string postalCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPostalCodeBytes() {
      java.lang.Object ref = postalCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        postalCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISCANADA_FIELD_NUMBER = 6;
    private boolean isCanada_;
    /**
     * <code>optional bool isCanada = 6;</code>
     */
    public boolean getIsCanada() {
      return isCanada_;
    }

    public static final int MAPTEST_FIELD_NUMBER = 7;
    private static final class MapTestDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.quancheng.saluki.serializer.proto.Message.internal_static_Address_MapTestEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> mapTest_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMapTest() {
      if (mapTest_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapTestDefaultEntryHolder.defaultEntry);
      }
      return mapTest_;
    }

    public int getMapTestCount() {
      return internalGetMapTest().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; mapTest = 7;</code>
     */

    public boolean containsMapTest(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMapTest().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapTestMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMapTest() {
      return getMapTestMap();
    }
    /**
     * <code>map&lt;string, string&gt; mapTest = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getMapTestMap() {
      return internalGetMapTest().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; mapTest = 7;</code>
     */

    public java.lang.String getMapTestOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMapTest().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; mapTest = 7;</code>
     */

    public java.lang.String getMapTestOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMapTest().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PHONETYPE_FIELD_NUMBER = 8;
    private int phoneType_;
    /**
     * <code>optional .Address.PhoneType phoneType = 8;</code>
     */
    public int getPhoneTypeValue() {
      return phoneType_;
    }
    /**
     * <code>optional .Address.PhoneType phoneType = 8;</code>
     */
    public com.quancheng.saluki.serializer.proto.Message.Address.PhoneType getPhoneType() {
      com.quancheng.saluki.serializer.proto.Message.Address.PhoneType result = com.quancheng.saluki.serializer.proto.Message.Address.PhoneType.valueOf(phoneType_);
      return result == null ? com.quancheng.saluki.serializer.proto.Message.Address.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStreetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, street_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
      }
      if (!getStateOrProvinceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stateOrProvince_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, country_);
      }
      if (!getPostalCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, postalCode_);
      }
      if (isCanada_ != false) {
        output.writeBool(6, isCanada_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMapTest().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        mapTest = MapTestDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(7, mapTest);
      }
      if (phoneType_ != com.quancheng.saluki.serializer.proto.Message.Address.PhoneType.MOBILE.getNumber()) {
        output.writeEnum(8, phoneType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStreetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, street_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      if (!getStateOrProvinceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, stateOrProvince_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, country_);
      }
      if (!getPostalCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, postalCode_);
      }
      if (isCanada_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isCanada_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMapTest().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        mapTest = MapTestDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, mapTest);
      }
      if (phoneType_ != com.quancheng.saluki.serializer.proto.Message.Address.PhoneType.MOBILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, phoneType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.quancheng.saluki.serializer.proto.Message.Address)) {
        return super.equals(obj);
      }
      com.quancheng.saluki.serializer.proto.Message.Address other = (com.quancheng.saluki.serializer.proto.Message.Address) obj;

      boolean result = true;
      result = result && getStreet()
          .equals(other.getStreet());
      result = result && getCity()
          .equals(other.getCity());
      result = result && getStateOrProvince()
          .equals(other.getStateOrProvince());
      result = result && getCountry()
          .equals(other.getCountry());
      result = result && getPostalCode()
          .equals(other.getPostalCode());
      result = result && (getIsCanada()
          == other.getIsCanada());
      result = result && internalGetMapTest().equals(
          other.internalGetMapTest());
      result = result && phoneType_ == other.phoneType_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STREET_FIELD_NUMBER;
      hash = (53 * hash) + getStreet().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + STATEORPROVINCE_FIELD_NUMBER;
      hash = (53 * hash) + getStateOrProvince().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + POSTALCODE_FIELD_NUMBER;
      hash = (53 * hash) + getPostalCode().hashCode();
      hash = (37 * hash) + ISCANADA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsCanada());
      if (!internalGetMapTest().getMap().isEmpty()) {
        hash = (37 * hash) + MAPTEST_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMapTest().hashCode();
      }
      hash = (37 * hash) + PHONETYPE_FIELD_NUMBER;
      hash = (53 * hash) + phoneType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.quancheng.saluki.serializer.proto.Message.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.quancheng.saluki.serializer.proto.Message.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        com.quancheng.saluki.serializer.proto.Message.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.quancheng.saluki.serializer.proto.Message.internal_static_Address_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMapTest();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableMapTest();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.quancheng.saluki.serializer.proto.Message.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.quancheng.saluki.serializer.proto.Message.Address.class, com.quancheng.saluki.serializer.proto.Message.Address.Builder.class);
      }

      // Construct using com.quancheng.saluki.serializer.proto.Message.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        street_ = "";

        city_ = "";

        stateOrProvince_ = "";

        country_ = "";

        postalCode_ = "";

        isCanada_ = false;

        internalGetMutableMapTest().clear();
        phoneType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.quancheng.saluki.serializer.proto.Message.internal_static_Address_descriptor;
      }

      public com.quancheng.saluki.serializer.proto.Message.Address getDefaultInstanceForType() {
        return com.quancheng.saluki.serializer.proto.Message.Address.getDefaultInstance();
      }

      public com.quancheng.saluki.serializer.proto.Message.Address build() {
        com.quancheng.saluki.serializer.proto.Message.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.quancheng.saluki.serializer.proto.Message.Address buildPartial() {
        com.quancheng.saluki.serializer.proto.Message.Address result = new com.quancheng.saluki.serializer.proto.Message.Address(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.street_ = street_;
        result.city_ = city_;
        result.stateOrProvince_ = stateOrProvince_;
        result.country_ = country_;
        result.postalCode_ = postalCode_;
        result.isCanada_ = isCanada_;
        result.mapTest_ = internalGetMapTest();
        result.mapTest_.makeImmutable();
        result.phoneType_ = phoneType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.quancheng.saluki.serializer.proto.Message.Address) {
          return mergeFrom((com.quancheng.saluki.serializer.proto.Message.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.quancheng.saluki.serializer.proto.Message.Address other) {
        if (other == com.quancheng.saluki.serializer.proto.Message.Address.getDefaultInstance()) return this;
        if (!other.getStreet().isEmpty()) {
          street_ = other.street_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getStateOrProvince().isEmpty()) {
          stateOrProvince_ = other.stateOrProvince_;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (!other.getPostalCode().isEmpty()) {
          postalCode_ = other.postalCode_;
          onChanged();
        }
        if (other.getIsCanada() != false) {
          setIsCanada(other.getIsCanada());
        }
        internalGetMutableMapTest().mergeFrom(
            other.internalGetMapTest());
        if (other.phoneType_ != 0) {
          setPhoneTypeValue(other.getPhoneTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.quancheng.saluki.serializer.proto.Message.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.quancheng.saluki.serializer.proto.Message.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object street_ = "";
      /**
       * <code>optional string street = 1;</code>
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          street_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public Builder setStreet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        street_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public Builder clearStreet() {
        
        street_ = getDefaultInstance().getStreet();
        onChanged();
        return this;
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public Builder setStreetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        street_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 2;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stateOrProvince_ = "";
      /**
       * <code>optional string stateOrProvince = 3;</code>
       */
      public java.lang.String getStateOrProvince() {
        java.lang.Object ref = stateOrProvince_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stateOrProvince_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stateOrProvince = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStateOrProvinceBytes() {
        java.lang.Object ref = stateOrProvince_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stateOrProvince_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stateOrProvince = 3;</code>
       */
      public Builder setStateOrProvince(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stateOrProvince_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stateOrProvince = 3;</code>
       */
      public Builder clearStateOrProvince() {
        
        stateOrProvince_ = getDefaultInstance().getStateOrProvince();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stateOrProvince = 3;</code>
       */
      public Builder setStateOrProvinceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stateOrProvince_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>optional string country = 4;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string country = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string country = 4;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 4;</code>
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 4;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object postalCode_ = "";
      /**
       * <code>optional string postalCode = 5;</code>
       */
      public java.lang.String getPostalCode() {
        java.lang.Object ref = postalCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          postalCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string postalCode = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPostalCodeBytes() {
        java.lang.Object ref = postalCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          postalCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string postalCode = 5;</code>
       */
      public Builder setPostalCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        postalCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string postalCode = 5;</code>
       */
      public Builder clearPostalCode() {
        
        postalCode_ = getDefaultInstance().getPostalCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string postalCode = 5;</code>
       */
      public Builder setPostalCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        postalCode_ = value;
        onChanged();
        return this;
      }

      private boolean isCanada_ ;
      /**
       * <code>optional bool isCanada = 6;</code>
       */
      public boolean getIsCanada() {
        return isCanada_;
      }
      /**
       * <code>optional bool isCanada = 6;</code>
       */
      public Builder setIsCanada(boolean value) {
        
        isCanada_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isCanada = 6;</code>
       */
      public Builder clearIsCanada() {
        
        isCanada_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> mapTest_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMapTest() {
        if (mapTest_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapTestDefaultEntryHolder.defaultEntry);
        }
        return mapTest_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMapTest() {
        onChanged();;
        if (mapTest_ == null) {
          mapTest_ = com.google.protobuf.MapField.newMapField(
              MapTestDefaultEntryHolder.defaultEntry);
        }
        if (!mapTest_.isMutable()) {
          mapTest_ = mapTest_.copy();
        }
        return mapTest_;
      }

      public int getMapTestCount() {
        return internalGetMapTest().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; mapTest = 7;</code>
       */

      public boolean containsMapTest(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMapTest().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapTestMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMapTest() {
        return getMapTestMap();
      }
      /**
       * <code>map&lt;string, string&gt; mapTest = 7;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getMapTestMap() {
        return internalGetMapTest().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; mapTest = 7;</code>
       */

      public java.lang.String getMapTestOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMapTest().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; mapTest = 7;</code>
       */

      public java.lang.String getMapTestOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMapTest().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMapTest() {
        getMutableMapTest().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; mapTest = 7;</code>
       */

      public Builder removeMapTest(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableMapTest().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMapTest() {
        return internalGetMutableMapTest().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; mapTest = 7;</code>
       */
      public Builder putMapTest(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableMapTest().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; mapTest = 7;</code>
       */

      public Builder putAllMapTest(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableMapTest().putAll(values);
        return this;
      }

      private int phoneType_ = 0;
      /**
       * <code>optional .Address.PhoneType phoneType = 8;</code>
       */
      public int getPhoneTypeValue() {
        return phoneType_;
      }
      /**
       * <code>optional .Address.PhoneType phoneType = 8;</code>
       */
      public Builder setPhoneTypeValue(int value) {
        phoneType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Address.PhoneType phoneType = 8;</code>
       */
      public com.quancheng.saluki.serializer.proto.Message.Address.PhoneType getPhoneType() {
        com.quancheng.saluki.serializer.proto.Message.Address.PhoneType result = com.quancheng.saluki.serializer.proto.Message.Address.PhoneType.valueOf(phoneType_);
        return result == null ? com.quancheng.saluki.serializer.proto.Message.Address.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .Address.PhoneType phoneType = 8;</code>
       */
      public Builder setPhoneType(com.quancheng.saluki.serializer.proto.Message.Address.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        phoneType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Address.PhoneType phoneType = 8;</code>
       */
      public Builder clearPhoneType() {
        
        phoneType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final com.quancheng.saluki.serializer.proto.Message.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.quancheng.saluki.serializer.proto.Message.Address();
    }

    public static com.quancheng.saluki.serializer.proto.Message.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    public com.quancheng.saluki.serializer.proto.Message.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>optional .Address address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional .Address address = 3;</code>
     */
    com.quancheng.saluki.serializer.proto.Message.Address getAddress();
    /**
     * <code>optional .Address address = 3;</code>
     */
    com.quancheng.saluki.serializer.proto.Message.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      age_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.quancheng.saluki.serializer.proto.Message.Address.Builder subBuilder = null;
              if (address_ != null) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.quancheng.saluki.serializer.proto.Message.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.quancheng.saluki.serializer.proto.Message.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.quancheng.saluki.serializer.proto.Message.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.quancheng.saluki.serializer.proto.Message.Person.class, com.quancheng.saluki.serializer.proto.Message.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private com.quancheng.saluki.serializer.proto.Message.Address address_;
    /**
     * <code>optional .Address address = 3;</code>
     */
    public boolean hasAddress() {
      return address_ != null;
    }
    /**
     * <code>optional .Address address = 3;</code>
     */
    public com.quancheng.saluki.serializer.proto.Message.Address getAddress() {
      return address_ == null ? com.quancheng.saluki.serializer.proto.Message.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>optional .Address address = 3;</code>
     */
    public com.quancheng.saluki.serializer.proto.Message.AddressOrBuilder getAddressOrBuilder() {
      return getAddress();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (address_ != null) {
        output.writeMessage(3, getAddress());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (address_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAddress());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.quancheng.saluki.serializer.proto.Message.Person)) {
        return super.equals(obj);
      }
      com.quancheng.saluki.serializer.proto.Message.Person other = (com.quancheng.saluki.serializer.proto.Message.Person) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (hasAddress() == other.hasAddress());
      if (hasAddress()) {
        result = result && getAddress()
            .equals(other.getAddress());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.quancheng.saluki.serializer.proto.Message.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.quancheng.saluki.serializer.proto.Message.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.quancheng.saluki.serializer.proto.Message.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.quancheng.saluki.serializer.proto.Message.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.quancheng.saluki.serializer.proto.Message.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.quancheng.saluki.serializer.proto.Message.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.quancheng.saluki.serializer.proto.Message.Person.class, com.quancheng.saluki.serializer.proto.Message.Person.Builder.class);
      }

      // Construct using com.quancheng.saluki.serializer.proto.Message.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          address_ = null;
          addressBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.quancheng.saluki.serializer.proto.Message.internal_static_Person_descriptor;
      }

      public com.quancheng.saluki.serializer.proto.Message.Person getDefaultInstanceForType() {
        return com.quancheng.saluki.serializer.proto.Message.Person.getDefaultInstance();
      }

      public com.quancheng.saluki.serializer.proto.Message.Person build() {
        com.quancheng.saluki.serializer.proto.Message.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.quancheng.saluki.serializer.proto.Message.Person buildPartial() {
        com.quancheng.saluki.serializer.proto.Message.Person result = new com.quancheng.saluki.serializer.proto.Message.Person(this);
        result.name_ = name_;
        result.age_ = age_;
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.quancheng.saluki.serializer.proto.Message.Person) {
          return mergeFrom((com.quancheng.saluki.serializer.proto.Message.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.quancheng.saluki.serializer.proto.Message.Person other) {
        if (other == com.quancheng.saluki.serializer.proto.Message.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.quancheng.saluki.serializer.proto.Message.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.quancheng.saluki.serializer.proto.Message.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private com.quancheng.saluki.serializer.proto.Message.Address address_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.quancheng.saluki.serializer.proto.Message.Address, com.quancheng.saluki.serializer.proto.Message.Address.Builder, com.quancheng.saluki.serializer.proto.Message.AddressOrBuilder> addressBuilder_;
      /**
       * <code>optional .Address address = 3;</code>
       */
      public boolean hasAddress() {
        return addressBuilder_ != null || address_ != null;
      }
      /**
       * <code>optional .Address address = 3;</code>
       */
      public com.quancheng.saluki.serializer.proto.Message.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? com.quancheng.saluki.serializer.proto.Message.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Address address = 3;</code>
       */
      public Builder setAddress(com.quancheng.saluki.serializer.proto.Message.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Address address = 3;</code>
       */
      public Builder setAddress(
          com.quancheng.saluki.serializer.proto.Message.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Address address = 3;</code>
       */
      public Builder mergeAddress(com.quancheng.saluki.serializer.proto.Message.Address value) {
        if (addressBuilder_ == null) {
          if (address_ != null) {
            address_ =
              com.quancheng.saluki.serializer.proto.Message.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Address address = 3;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          address_ = null;
          addressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Address address = 3;</code>
       */
      public com.quancheng.saluki.serializer.proto.Message.Address.Builder getAddressBuilder() {
        
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Address address = 3;</code>
       */
      public com.quancheng.saluki.serializer.proto.Message.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              com.quancheng.saluki.serializer.proto.Message.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>optional .Address address = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.quancheng.saluki.serializer.proto.Message.Address, com.quancheng.saluki.serializer.proto.Message.Address.Builder, com.quancheng.saluki.serializer.proto.Message.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.quancheng.saluki.serializer.proto.Message.Address, com.quancheng.saluki.serializer.proto.Message.Address.Builder, com.quancheng.saluki.serializer.proto.Message.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final com.quancheng.saluki.serializer.proto.Message.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.quancheng.saluki.serializer.proto.Message.Person();
    }

    public static com.quancheng.saluki.serializer.proto.Message.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public com.quancheng.saluki.serializer.proto.Message.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_MapTestEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_MapTestEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"\243\002\n\007Address\022\016\n\006street\030\001 " +
      "\001(\t\022\014\n\004city\030\002 \001(\t\022\027\n\017stateOrProvince\030\003 \001" +
      "(\t\022\017\n\007country\030\004 \001(\t\022\022\n\npostalCode\030\005 \001(\t\022" +
      "\020\n\010isCanada\030\006 \001(\010\022&\n\007mapTest\030\007 \003(\0132\025.Add" +
      "ress.MapTestEntry\022%\n\tphoneType\030\010 \001(\0162\022.A" +
      "ddress.PhoneType\032.\n\014MapTestEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"+\n\tPhoneType\022\n\n" +
      "\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\">\n\006Person\022" +
      "\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\031\n\007address\030\003 " +
      "\001(\0132\010.AddressB0\n%com.quancheng.saluki.se",
      "rializer.protoB\007Messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Street", "City", "StateOrProvince", "Country", "PostalCode", "IsCanada", "MapTest", "PhoneType", });
    internal_static_Address_MapTestEntry_descriptor =
      internal_static_Address_descriptor.getNestedTypes().get(0);
    internal_static_Address_MapTestEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_MapTestEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
