/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shimingliu' at '16-11-1 上午11:55' with Gradle 3.0
 *
 * @author shimingliu, @date 16-11-1 上午11:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
